### ISSUE TITLE
certbot | nc: Bad address 'nginx' Waiting for nginx to start...

### ISSUE THREAD

**Issue by ydrea** [opencontext/arches-via-docker#1]
Hi!
It seems stuck in a loop:
```

arches_elasticsearch  | {"type": "server", "timestamp": "2023-06-06T21:38:51,889Z", "level": "WARN", "component": "o.e.c.r.a.DiskThresholdMonitor", "cluster.name": "docker-cluster", "node.name": "b59ccac7b2e0", "message": "high disk watermark [90%] exceeded on [xOL5lElPTg2I-IlJSAThNQ][b59ccac7b2e0][/usr/share/elasticsearch/data/nodes/0] free: 9.9gb[9.2%], shards will be relocated away from this node; currently relocating away shards totalling [0] bytes; the node is expected to continue to exceed the high disk watermark when these relocations are complete", "cluster.uuid": "ygfP61AXRmuRbmrbCJcB_Q", "node.id": "xOL5lElPTg2I-IlJSAThNQ"  }
certbot               | nc: bad address 'nginx'
certbot               | Waiting for nginx to start...
certbot               | nc: bad address 'nginx'
certbot               | Waiting for nginx to start...
certbot               | nc: bad address 'nginx'
certbot               | Waiting for nginx to start...
certbot               | nc: bad address 'nginx'
certbot               | Waiting for nginx to start...
```

My .env file is:
```
# Edit this file and save as ".env" for use.

COMPOSE_PROJECT_NAME=suhi
DOMAINS=localhost
DEPLOY_HOST=localhost
NGINX_HTML_PATH=/var/www/html/$DEPLOY_HOST
CERT_PATH=/var/www/certbot/$DEPLOY_HOST
CERTBOT_EMAILS=ydrea.wrld@gmail.com
CERTBOT_TEST_CERT=1
CERTBOT_RSA_KEY_SIZE=4096
TZ=PST

#arches project and paths
ARCHES_PROJECT=suhozid
ARCHES_ROOT=/suhozid_app
APP_ROOT=$ARCHES_ROOT/$ARCHES_PROJECT
APP_COMP_FOLDER=$APP_ROOT/$ARCHES_PROJECT

#Arches configs
# NOTE: the ARCHES_NAMESPACE needs to look like a URL, ending in a '/',
# with the same port as used by the Arches Django APP.
ARCHES_NAMESPACE='http://localhost:8000/'
# This will hopefully make the yarn build not fail.
NODE_OPTIONS='--max-old-space-size=1024'
INSTALL_DEFAULT_GRAPHS=True
INSTALL_DEFAULT_CONCEPTS=True
# Don't change these, because I can't figure out how dynamically pass
# a new database password to Postgres via docker compose. If you change
# something like the PGPASSWORD, be sure to change it in the corresponding
# value in the docker-compse.yml for the Postgres container.
PGUSERNAME=postgres
PGPASSWORD=postgis
PGDBNAME=$ARCHES_PROJECT
PGHOST=arches_db
PGPORT=5432
ESHOST=arches_elasticsearch
ESPORT=9200
DJANGO_MODE=DEV
DJANGO_DEBUG=False
# Don't change the port, since it's pretty hard-coded.
DJANGO_PORT=8000
DOMAIN_NAMES=$DOMAINS localhost 0.0.0.0 127.0.0.1
# NOTE: Only set BUILD_PRODUCTION=True if you have well over
# 8GB of system RAM. Otherwise, yarn will likely error out.
BUILD_PRODUCTION=False
PYTHONUNBUFFERED=0
ELASTICSEARCH_PREFIX=$ARCHES_PROJECT

# RabbitMQ credentials. We're currently using Redis as a task
# broker, not RabbitMQ, so these are commented out.
# RABBITMQ_USER=guest
# RABBITMQ_PASS=guest

# couchdb for arches. Not needed for V7+, but config exists incase it
# reappears.
COUCHDB_HOST=arches
COUCHDB_PORT=5984
COUCHDB_USER=admin
COUCHDB_PASS=password
COUCHDB_URL=http://$COUCHDB_USER:$COUCHDB_PASS@$COUCHDB_HOST:$COUCHDB_PORT

# The DATABASE_URL is a convenience consolidated way help connect to Postgresql
# pg_featureserv and tileserv
DATABASE_URL=postgresql://$PGUSERNAME:$PGPASSWORD@$PGHOST/$PGDBNAME
```

**Comment by ekansa** [comment]
@ydrea Ah! Perhaps I should start a separate branch for using this in a localhost scenario. Nginx and certbot are more suited for Web deployments, and they greatly complicate things when running locally.

Do you think a branch with a localhost only deployment would be useful?

**Comment by ydrea** [comment]
> @ydrea Ah! Perhaps I should start a separate branch for using this in a localhost scenario. Nginx and certbot are more suited for Web deployments, and they greatly complicate things when running locally.

I see... Gonna try it with a real domain tomorrow ;) 
> 
> Do you think a branch with a localhost only deployment would be useful?
 
I believe it would - it is the primary way for trying out new stuff!

**Comment by ydrea** [comment]
slightly different, but still a loop:
```
with contents: 
nginx                              | hello.txt
nginx                              | Waiting for Let's Encrypt certificates for ec2-3-120-225-95.eu-central-1.compute.amazonaws.com
nginx                              | CERT_PATH is apparently /var/www/certbot/ec2-3-120-225-95.eu-central-1.compute.amazonaws.com, 
```

**Comment by ekansa** [comment]
@ydrea 

Perhaps there's an issue with the setting `CERTBOT_TEST_CERT=1`

Can you try again with `CERTBOT_TEST_CERT=0` ?

**Comment by ydrea** [comment]
I have! Unfortunately:
```

nginx                 | Waiting for Let's Encrypt certificates for ec2-3-71-26-133.eu-central-1.compute.amazonaws.com
nginx                 | CERT_PATH is apparently /var/www/certbot/ec2-3-71-26-133.eu-central-1.compute.amazonaws.com, with contents: 
nginx                 | hello.txt
```

**Comment by ydrea** [comment]
sorry, just noticed - it's up!

**Comment by ydrea** [comment]
arches_webpack        | ----- *** RUNNING WEBPACK SERVER FOR SETUP *** -----
arches_webpack        | 
arches_webpack        | We (apparently) have yet to run webpack and collectstatic. Do it now!
arches_webpack        | Running Webpack, hopefully the build_production thing will work!
arches_webpack        | yarn install v1.22.19
arches_webpack        | [1/4] Resolving packages...
arches_webpack        | success Already up-to-date.
arches_webpack        | Done in 0.05s.
arches_webpack        | Unknown command: 'build_production'
arches_webpack        | Type 'manage.py help' for usage.

**Comment by ydrea** [comment]
another loop, webpack related...

**Comment by ekansa** [comment]
I just tried the `python3 manage.py build_production` command on my instance and it executed (though I didn't run it to completion because I don't have enough available memory). The Farallon folks said that you need to have a relatively high memory machine for a production Webpack build (which gets invoked by `build_production`) to run. I haven't tried to fully test it, since I don't have the budget to spend on an high memory server instance. 

But the arches_webpack output you provided suggests a different problem that's not memory related. It looks like `build_production` is not recognized by manage.py? I haven't encountered that problem before.  

Let's see if we can diagnose the problem:

I recommend that you go back to the development build (with `BUILD_PRODUCTION=False`) and rebuild your deployment. Hopefully that will work? 

Then, once Docker compose has finished and all the containers are running, try to log into the arches container with:
`docker exec -it arches bash` (this is like ssh-ing into the container)

Once you're in, you can try to invoke the `build_production` management command on Arches:
```
root@89d4bfd5eb82:/arches_app/arches_proj# python3 manage.py build_production
```

It will be good to know if you get the `Unknown command: 'build_production'` in this situation.

**Comment by ydrea** [comment]
yup, as you have assumed:

```
root@86fd83d108a7:/suhozid_app/suhozid# python3 manage.py build_production
Unknown command: 'build_production'
Type 'manage.py help' for usage.
```

**Comment by ekansa** [comment]
That's strange! Are you attempting to install a prior version of Arches?

**Comment by ydrea** [comment]
yes, I need v6!

**Comment by ekansa** [comment]
@ydrea OK! I made updates to the [v6 branch](https://github.com/opencontext/arches-via-docker/tree/v6) to remove the v7 `build_production` command and replace it with the v6 `build` command. I just tested it and it seems to work on my instance. 

Let me know if it works for you!

**Comment by ekansa** [comment]
@ydrea Given the apparent success you mentioned in the Arches forum (https://community.archesproject.org/t/arches-on-aws-ec2-rds-s3/2002?u=ekansa), I'm going to close this issue now.
