### ISSUE TITLE
AFS dev/1.1.x - Error settings attribute file formats

### ISSUE THREAD

**Issue by rayondemiel** [opencontext/arches-via-docker#4]
Hi !
During my test phase, I noticed a configuration problem. Wrong configuration attribute name for file format. 

"INSTRUMENT_FILE_FORMATS" -> "XY_TEXT_FILE_FORMATS"

Source : https://github.com/archesproject/arches-for-science/tree/dev/1.1.x

**Comment by ekansa** [comment]
Thanks for this fix! I approved and merged your PR. https://github.com/opencontext/arches-via-docker/pull/5
